/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ab2ds.panels;

import com.ab2ds.core.MainFrame;
import com.ab2ds.dialog.ScriptManagerDialog;
import com.ab2ds.util.EngineParser;
import com.ab2ds.util.XMLEngine;
import com.falcron.graphics.core.SimpleText;
import com.falcron.graphics.scene.SimpleScene;
import com.falcron.sprite.AnimatedSprite;
import com.falcron.sprite.Entity;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.w3c.dom.Element;

/**
 *
 * @author prk
 */
public class EntityPropertyPanel extends javax.swing.JPanel {
    
    private Entity entity;
    private SimpleScene scene;
    private MainFrame mainframe;
    
    public EntityPropertyPanel(MainFrame mainframe) {
        initComponents();
        this.mainframe = mainframe;
        setSize(getPreferredSize());
    }
    
    public void setEntity(Entity entity, SimpleScene scene){
        this.entity = entity;
        this.scene = scene;
        jtfName.setText(this.entity.name);
        jspwidth.setValue(this.entity.width);
        jspheight.setValue(this.entity.height);
        jspx.setValue(this.entity.location.x);
        jspy.setValue(this.entity.location.y);
        jcbdebug.setSelected(this.entity.debug);
        jspcrot.setValue(this.entity.centerRotation.getRotation());
        jcbrender.setSelected(entity.render);
        //jbtScriptManager.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jspwidth = new javax.swing.JSpinner();
        jspheight = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jcbdebug = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jspx = new javax.swing.JSpinner();
        jspy = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtdel = new javax.swing.JButton();
        jspcrot = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jbtScriptManager = new javax.swing.JButton();
        jcbrender = new javax.swing.JCheckBox();
        jbtgo = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Entity Property"));
        setPreferredSize(new java.awt.Dimension(419, 300));

        jLabel1.setText("Name");

        jtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNameKeyReleased(evt);
            }
        });

        jLabel2.setText("Width");

        jspwidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspwidthStateChanged(evt);
            }
        });

        jspheight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspheightStateChanged(evt);
            }
        });

        jLabel3.setText("Height");

        jcbdebug.setText("Debug Mode");
        jcbdebug.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbdebugStateChanged(evt);
            }
        });
        jcbdebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdebugActionPerformed(evt);
            }
        });

        jLabel4.setText("Location");

        jspx.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspxStateChanged(evt);
            }
        });

        jspy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspyStateChanged(evt);
            }
        });

        jLabel5.setText("X");

        jLabel6.setText("Y");

        jbtdel.setText("Delete");
        jbtdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdelActionPerformed(evt);
            }
        });

        jspcrot.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspcrotStateChanged(evt);
            }
        });

        jLabel7.setText("Rotation");

        jbtScriptManager.setText("Script Manager");
        jbtScriptManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtScriptManagerActionPerformed(evt);
            }
        });

        jcbrender.setText("Render");
        jcbrender.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbrenderStateChanged(evt);
            }
        });

        jbtgo.setText("Save as XMLObject");
        jbtgo.setToolTipText("<html>\n<b>\nXML Object is the game object that is stored under the XML format in objects package so that it can be instantiated at any time\n</b>\n</html>");
        jbtgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtgoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jspx, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspy, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtdel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jspwidth, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jspheight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel2)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jspcrot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbdebug)
                        .addGap(18, 18, 18)
                        .addComponent(jcbrender)))
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtScriptManager, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtgo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jspwidth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfName)
                    .addComponent(jspheight)
                    .addComponent(jspcrot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jspx)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jspy)
                    .addComponent(jbtdel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbdebug)
                    .addComponent(jcbrender))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtScriptManager)
                    .addComponent(jbtgo))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameKeyReleased
        if(entity != null){
            entity.name = jtfName.getText();
        }
    }//GEN-LAST:event_jtfNameKeyReleased

    private void jspwidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspwidthStateChanged
        if(entity != null){
            entity.width = Integer.parseInt(jspwidth.getValue().toString());
        }
    }//GEN-LAST:event_jspwidthStateChanged

    private void jspheightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspheightStateChanged
        if(entity != null){
            entity.height = Integer.parseInt(jspheight.getValue().toString());
        }
    }//GEN-LAST:event_jspheightStateChanged

    private void jspxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspxStateChanged
        if(entity != null){
            entity.location.x = Float.parseFloat(jspx.getValue().toString());
        }
    }//GEN-LAST:event_jspxStateChanged

    private void jspyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspyStateChanged
        if(entity != null){
            entity.location.y = Float.parseFloat(jspy.getValue().toString());
        }
    }//GEN-LAST:event_jspyStateChanged

    private void jcbdebugStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbdebugStateChanged
        entity.debug = jcbdebug.isSelected();
    }//GEN-LAST:event_jcbdebugStateChanged

    private void jspcrotStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspcrotStateChanged
        entity.centerRotation.setRotation(Float.parseFloat(jspcrot.getValue().toString()));
    }//GEN-LAST:event_jspcrotStateChanged

    private void jcbdebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdebugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbdebugActionPerformed

    private void jbtdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdelActionPerformed
        scene.deleteRenderable(entity);
    }//GEN-LAST:event_jbtdelActionPerformed

    private void jbtScriptManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtScriptManagerActionPerformed
        ScriptManagerDialog s = new ScriptManagerDialog(entity, mainframe);
        s.setVisible(true);
    }//GEN-LAST:event_jbtScriptManagerActionPerformed

    private void jcbrenderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbrenderStateChanged
        entity.render = jcbrender.isSelected();
    }//GEN-LAST:event_jcbrenderStateChanged

    private void jbtgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtgoActionPerformed
        mainframe.filechooser.setSelectedFile(new File(mainframe.getProjectAbsPath()+"/project/src/com/objects/NewObject"));
        int n = mainframe.filechooser.showSaveDialog(null);
        if(n == JFileChooser.APPROVE_OPTION){
            File f = new File(mainframe.getProjectAbsPath()+"/project/src/com/objects/"+mainframe.filechooser.getSelectedFile().getName()+".xml");
            XMLEngine xml = new XMLEngine();
            Element exmlobj = xml.appendRoot("xmlobject");
           if(entity instanceof SimpleText){
                EngineParser.parseSimpleText(xml, exmlobj, (SimpleText) entity);
            }else if(entity instanceof AnimatedSprite){
                AnimatedSprite as = (AnimatedSprite) entity;
                EngineParser.parseAnimatedSprite(xml, exmlobj, as, as.imageresource.path, as.imageresource.resourcename);
            }
            xml.save(f.getAbsolutePath());
            JOptionPane.showMessageDialog(null, "XML Object is saved", "Entity Manager", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtgoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtScriptManager;
    private javax.swing.JButton jbtdel;
    private javax.swing.JButton jbtgo;
    private javax.swing.JCheckBox jcbdebug;
    private javax.swing.JCheckBox jcbrender;
    private javax.swing.JSpinner jspcrot;
    private javax.swing.JSpinner jspheight;
    private javax.swing.JSpinner jspwidth;
    private javax.swing.JSpinner jspx;
    private javax.swing.JSpinner jspy;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
